"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from shutil import which

from dotenv import load_dotenv

from django.utils.translation import gettext_lazy as _

# Load environment variables from .env
load_dotenv(Path(__file__).resolve().parent.parent.parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get("DJANGO_DEBUG") == "True" else False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',

    # Third-party apps
    "rosetta",
    "phonenumber_field",
    "tailwind",
    "mptt",
    "django_ckeditor_5",

    # Local apps
    'account',
    'main',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.default',
            ],
            'libraries': {
                'main_tags': 'main.templatetags.main_tags',
                'blog_tags': 'blog.templatetags.blog_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
USE_TZ = True
USE_I18N = True
USE_L10N = True
TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en', _('English')),
    ('fa', _('Persian')),
)
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

# Rosetta configuration
# https://django-rosetta.readthedocs.io/
ROSETTA_MESSAGES_PER_PAGE = 100
ROSETTA_SHOW_AT_ADMIN_PANEL = True
# ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = "en-us"
# ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = "English"
# ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = True
# GOOGLE_APPLICATION_CREDENTIALS_PATH = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS_PATH")
# GOOGLE_PROJECT_ID = os.environ.get("GOOGLE_PROJECT_ID")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = "account.User"

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'account.backends.EmailBackend',
    'account.backends.PhoneBackend',
]

# Set the timeout days for the reset link
# PASSWORD_RESET_TIMEOUT_DAYS = 3

# Custom email template for password reset
# PASSWORD_RESET_EMAIL_TEMPLATE_NAME = "auth/password-reset-email.html"

SITE_NAME = _("Django Blog")
ALLOW_UNICODE_SLUGS = True

INTERNAL_IPS = [
    "127.0.0.1",
]

ALLOWED_IMAGE_EXTENSIONS = ["jpg", "jpeg", "png", "gif", "webp"]
MAX_IMAGE_SIZE = 1024  # in KB

# Tailwind CSS
TAILWIND_APP_NAME = 'main'
NPM_BIN_PATH = which("npm")
TAILWIND_CSS_PATH = 'assets/css/style.min.css'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'db': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'db.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['db'],
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG',
    },
}

# CKEditor 5
# CKEDITOR_5_CUSTOM_CSS = 'path_to.css'  # optional
# CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage"  # optional
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]
customColors = [
    {
        "color": 'hsl(0, 0%, 0%)',
        "label": 'Black'
    },
    {
        "color": 'hsl(0, 0%, 30%)',
        "label": 'Dim grey'
    },
    {
        "color": 'hsl(0, 0%, 60%)',
        "label": 'Grey'
    },
    {
        "color": 'hsl(0, 0%, 90%)',
        "label": 'Light grey'
    },
    {
        "color": 'hsl(0, 0%, 100%)',
        "label": 'White',
        "hasBorder": True
    },
    {
        "color": 'hsl(0, 75%, 60%)',
        "label": 'Red'
    },
    {
        "color": 'hsl(30, 75%, 60%)',
        "label": 'Orange'
    },
    {
        "color": 'hsl(60, 75%, 60%)',
        "label": 'Yellow'
    },
    {
        "color": 'hsl(90, 75%, 60%)',
        "label": 'Light green'
    },
    {
        "color": 'hsl(120, 75%, 60%)',
        "label": 'Green'
    },
    {
        "color": 'hsl(150, 75%, 60%)',
        "label": 'Aquamarine'
    },
    {
        "color": 'hsl(180, 75%, 60%)',
        "label": 'Turquoise'
    },
    {
        "color": 'hsl(210, 75%, 60%)',
        "label": 'Light blue'
    },
    {
        "color": 'hsl(240, 75%, 60%)',
        "label": 'Blue'
    },
    {
        "color": 'hsl(270, 75%, 60%)',
        "label": 'Purple'
    },
    {
        "color": 'hsl(300, 75%, 60%)',
        "label": 'Pink'
    },
    {
        "color": 'hsl(330, 75%, 60%)',
        "label": 'Magenta'
    },
    {
        "color": 'hsl(45, 75%, 60%)',
        "label": 'Gold'
    },
    {
        "color": 'hsl(75, 75%, 60%)',
        "label": 'Olive'
    },
    {
        "color": 'hsl(105, 75%, 60%)',
        "label": 'Lime'
    },
    {
        "color": 'hsl(135, 75%, 60%)',
        "label": 'Teal'
    },
    {
        "color": 'hsl(165, 75%, 60%)',
        "label": 'Cyan'
    },
    {
        "color": 'hsl(195, 75%, 60%)',
        "label": 'Sky blue'
    },
    {
        "color": 'hsl(225, 75%, 60%)',
        "label": 'Navy'
    },
    {
        "color": 'hsl(255, 75%, 60%)',
        "label": 'Indigo'
    },
    {
        "color": 'hsl(285, 75%, 60%)',
        "label": 'Violet'
    },
    {
        "color": 'hsl(315, 75%, 60%)',
        "label": 'Rose'
    },
    {
        "color": 'hsl(15, 75%, 60%)',
        "label": 'Sunset'
    },
    {
        "color": 'hsl(135, 90%, 60%)',
        "label": 'Bright Cyan'
    },
    {
        "color": 'hsl(270, 40%, 60%)',
        "label": 'Pastel Purple'
    },
    {
        "color": 'hsl(60, 90%, 60%)',
        "label": 'Intense Yellow'
    },
    {
        "color": 'hsl(90, 60%, 60%)',
        "label": 'Lemon'
    },
    {
        "color": 'hsl(210, 40%, 60%)',
        "label": 'Powder Blue'
    },
    {
        "color": 'hsl(120, 60%, 60%)',
        "label": 'Emerald'
    },
    {
        "color": 'hsl(30, 60%, 60%)',
        "label": 'Vivid Orange'
    },
    {
        "color": 'hsl(225, 50%, 60%)',
        "label": 'Sky'
    },
    {
        "color": 'hsl(150, 70%, 60%)',
        "label": 'Mint'
    },
    {
        "color": 'hsl(300, 70%, 60%)',
        "label": 'Candy Pink'
    },
    {
        "color": 'hsl(330, 60%, 60%)',
        "label": 'Lavender'
    },
    {
        "color": 'hsl(180, 90%, 60%)',
        "label": 'Hot Pink'
    },
]
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "styles",
            "heading",
            "|",
            "bold",
            "italic",
            "Underline",
            "link",
            "|",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "alignment",
        ],
    },
    "comment": {
        "language": {"ui": "en", "content": "en"},  # Todo: check docs
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "admin": {
        "language": "en",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote"
        ],
        "toolbar": [
            "undo",
            "redo",
            "|",
            "heading",
            "codeBlock",
            "|",
            "outdent",
            "indent",
            "|",
            "bold",
            "italic",
            "link",
            "underline",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "alignment",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing",
            "|",
            "horizontalLine",
        ],
        "fontColor": {
            "colors": customColors
        },
        "fontBackgroundColor": {
            "colors": customColors
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:full",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter"
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties"
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette
            }
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph"
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1"
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2"
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3"
                },
                {
                    "model": "heading4",
                    "view": "h4",
                    "title": "Heading 4",
                    "class": "ck-heading_heading4"
                },
                {
                    "model": "heading5",
                    "view": "h5",
                    "title": "Heading 5",
                    "class": "ck-heading_heading5"
                },
                {
                    "model": "heading6",
                    "view": "h6",
                    "title": "Heading 6",
                    "class": "ck-heading_heading6"
                }
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
        "simpleUpload": {
            "uploadUrl": "/uploads/"
        },
        "link": {
            "addTargetToExternalLinks": True
        },
        "extraPlugins": [
            "Essentials", "CodeBlock", "Autoformat", "Bold", "Italic", "Underline", "Strikethrough", "Code", "Subscript", "Superscript", "BlockQuote", "Heading", "Image",
            "ImageCaption", "ImageStyle", "ImageToolbar", "ImageResize", "Link", "List", "Paragraph", "Alignment", "Font", "PasteFromOffice", "SimpleUploadAdapter",
            "MediaEmbed", "RemoveFormat", "Table", "TableToolbar", "TableCaption", "TableProperties", "TableCellProperties", "Indent", "IndentBlock", "Highlight", "TodoList",
            "ListProperties", "SourceEditing", "GeneralHtmlSupport", "ImageInsert", "WordCount", "Mention", "Style", "HorizontalLine", "LinkImage"
        ]
    }
}
