services:
  django:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: django
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/:/usr/src
    networks:
      - django_network
      - nginx_network
    env_file:
      - ./.env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - django_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/staticfiles/:/usr/src/staticfiles
      - ./src/media/:/usr/src/media
      - ./src/logs/:/usr/src/logs
    depends_on:
      - django

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - django_network
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD:-12345678}
    volumes:
      - ./data/redis:/data

volumes:
  postgres_data:
  redis_data:

networks:
  nginx_network:
  django_network:
